import type { SimParams } from './types';

export const defaultParams: SimParams = {
  N: 125,
  L: 10,
  K: 2,
  R_visual: 1,
  D: 0.02,
  omega0: 1,
  sigma_omega: 0.5,
  dt: 0.01,
  speed: 5,
  sigma_flash: 0.25,
  flashMode: 'spike',
  epsilon_city: 0,
  Omega_city: 1,
  phi_city: 0,
  obstacleRadius: 0.7,
  blockVisibility: true,
  speciesMode: 1,
  omega_A: 0.85,
  omega_B: 1.25,
  K_in: 2.4,
  K_out: 0.8,
  mobilityEnabled: true,
  v_firefly: 0.25,
  D_turn: 0.35,
  D_move: 0.02,
  R_avoid: 1.2,
  chi_bat: 1.1,
  predationEnabled: true,
  batCount: 0,
  v_bat: 0.8,
  R_bat_perception: 2.8,
  R_capture: 0.16,
  batTurnNoise: 0.25
};

export const presets: Record<string, Partial<SimParams>> = {
  'Random Field': { K: 0.4, R_visual: 2.2, D: 0.05, epsilon_city: 0, speciesMode: 1 },
  'Strong Coupling': { K: 4.2, R_visual: 4.6, D: 0.01, epsilon_city: 0, speciesMode: 1 },
  'Weak Coupling': { K: 0.6, R_visual: 1.8, D: 0.04, epsilon_city: 0, speciesMode: 1 },
  'Local Islands': { K: 3.5, R_visual: 1.8, D: 0.015, epsilon_city: 0, speciesMode: 1 },
  'City Light': { K: 1.3, R_visual: 3.6, D: 0.02, epsilon_city: 1.3, Omega_city: 1.35 },
  'Forest Barriers': { K: 2.8, R_visual: 3.8, D: 0.02, obstacleRadius: 1.2, blockVisibility: true },
  'Two Species': { K: 2, speciesMode: 2, omega_A: 0.75, omega_B: 1.35, K_in: 2.8, K_out: 0.4 },
  'Predator Avoidance': { mobilityEnabled: true, batCount: 3, v_firefly: 0.32, v_bat: 0.9, R_avoid: 1.6, chi_bat: 1.8, R_bat_perception: 3.2, R_capture: 0.16 },
  'High Mobility Swarm': { mobilityEnabled: true, batCount: 0, v_firefly: 0.55, D_turn: 0.7, D_move: 0.05, K: 2.2, R_visual: 3.2 }
};

export const paramIds = {
  N: 0,
  L: 1,
  K: 2,
  R_visual: 3,
  D: 4,
  omega0: 5,
  sigma_omega: 6,
  dt: 7,
  sigma_flash: 8,
  epsilon_city: 9,
  Omega_city: 10,
  phi_city: 11,
  blockVisibility: 12,
  speciesMode: 13,
  omega_A: 14,
  omega_B: 15,
  K_in: 16,
  K_out: 17,
  flashMode: 18,
  mobilityEnabled: 19,
  v_firefly: 20,
  D_turn: 21,
  D_move: 22,
  R_avoid: 23,
  chi_bat: 24,
  predationEnabled: 25,
  batCount: 26,
  v_bat: 27,
  R_bat_perception: 28,
  R_capture: 29,
  batTurnNoise: 30
} as const;
